CREATE DATABASE DOIT;
USE DOIT;

CREATE TABLE TIPO_FUNCIONARIO(
  ID_TIPO_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_TIPO_FUNCIONARIO)
);

CREATE TABLE STATUS(
  ID_STATUS INT NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_STATUS) 
);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL, 
  SENHA VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255)NOT NULL,
  FK_TIPO_FUNCIONARIO INT NOT NULL,
  PRIMARY KEY (ID_FUNCIONARIO),
  FOREIGN KEY (FK_TIPO_FUNCIONARIO) REFERENCES TIPO_FUNCIONARIO(ID_TIPO_FUNCIONARIO)
);

CREATE TABLE PROJETO(
  ID_PROJETO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(200) NOT NULL,
  FK_FUNCIONARIO INT,
  PRIMARY KEY(ID_PROJETO),
  FOREIGN KEY (FK_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE TABLE EQUIPE(
  ID_EQUIPE INT NOT NULL AUTO_INCREMENT,
  FK_PROJETO INT NOT NULL,
  FK_FUNCIONARIO INT NOT NULL,
  PRIMARY KEY (ID_EQUIPE),
  FOREIGN KEY (FK_PROJETO) REFERENCES PROJETO (ID_PROJETO),
  FOREIGN KEY (FK_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE TABLE TAREFA(
  ID_TAREFA INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NOT NULL,
  TITULO VARCHAR(100) NOT NULL,
  FK_FUNCIONARIO INT NOT NULL,
  FK_STATUS INT NOT NULL,
  FK_PROJETO INT NOT NULL,
  PRIMARY KEY(ID_TAREFA),
  FOREIGN KEY (FK_STATUS) REFERENCES STATUS(ID_STATUS),
  FOREIGN KEY (FK_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
  FOREIGN KEY (FK_PROJETO) REFERENCES PROJETO(ID_PROJETO)
);

INSERT INTO TIPO_FUNCIONARIO(DESCRICAO) VALUES
('ADMINISTRADOR'),
('GERENTE'),
('COLABORADOR');

INSERT INTO FUNCIONARIO(NOME, EMAIL, SENHA, FK_TIPO_FUNCIONARIO) VALUES
('Kleber', 'kleberlcaldas@gmail.com', '698dc19d489c4e4db73e28a713eab07b', 1),
('Deborah', 'deborah@teste.com', '3d9188577cc9bfe9291ac66b5cc872b7', 1),
('Piettro', 'piettro@teste.com', '3d9188577cc9bfe9291ac66b5cc872b7', 1);


INSERT INTO STATUS(TIPO) VALUES ('NOVO'), ('EM ANDAMENTO'), ('FINALIZADO');