-- MySQL Script generated by MySQL Workbench
-- Sat May 20 17:29:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema doit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doit` DEFAULT CHARACTER SET utf8 ;
USE `doit` ;

-- -----------------------------------------------------
-- Table `doit`.`STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`STATUS` ;

CREATE TABLE IF NOT EXISTS `doit`.`STATUS` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`PROJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`PROJETO` ;

CREATE TABLE IF NOT EXISTS `doit`.`PROJETO` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `gerente` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`TAREFA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`TAREFA` ;

CREATE TABLE IF NOT EXISTS `doit`.`TAREFA` (
  `id_tarefa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `fk_status` INT NOT NULL,
  `fk_projeto` INT NOT NULL,
  PRIMARY KEY (`id_tarefa`, `fk_status`, `fk_projeto`),
  INDEX `fk_status_idx` (`fk_status` ASC),
  INDEX `fk_projeto_idx` (`fk_projeto` ASC),
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `doit`.`STATUS` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `doit`.`PROJETO` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`TIPO_FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`TIPO_FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `doit`.`TIPO_FUNCIONARIO` (
  `id_tipo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tipo_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `doit`.`FUNCIONARIO` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `fk_tipo_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `fk_tipo_funcionario`),
  INDEX `fk_tipo_funcionario_idx` (`fk_tipo_funcionario` ASC),
  CONSTRAINT `fk_tipo_funcionario`
    FOREIGN KEY (`fk_tipo_funcionario`)
    REFERENCES `doit`.`TIPO_FUNCIONARIO` (`id_tipo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`COMENTARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`COMENTARIO` ;

CREATE TABLE IF NOT EXISTS `doit`.`COMENTARIO` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `fk_funcionario` INT NOT NULL,
  `fk_tarefa` INT NOT NULL,
  PRIMARY KEY (`id_comentario`, `fk_funcionario`, `fk_tarefa`),
  INDEX `fk_funcionario_idx` (`fk_funcionario` ASC),
  INDEX `fk_tarefa_idx` (`fk_tarefa` ASC),
  CONSTRAINT `fk_funcionario`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `doit`.`FUNCIONARIO` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefa`
    FOREIGN KEY (`fk_tarefa`)
    REFERENCES `doit`.`TAREFA` (`id_tarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doit`.`FUNCIONARIO_PROJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doit`.`FUNCIONARIO_PROJETO` ;

CREATE TABLE IF NOT EXISTS `doit`.`FUNCIONARIO_PROJETO` (
  `id_funcionario_projeto` INT NOT NULL AUTO_INCREMENT,
  `fk_projeto` INT NOT NULL,
  `fk_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario_projeto`),
  INDEX `fk_projeto_idx` (`fk_projeto` ASC),
  INDEX `fk_funcionario_idx` (`fk_funcionario` ASC),
  CONSTRAINT `fk_projeto`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `doit`.`PROJETO` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `doit`.`FUNCIONARIO` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
